-- Do not edit, file generated by GEN_AXI.py
library ieee;
use ieee.std_logic_1164.all;

package ver_pkg is
  constant GC_FPGA_REV_RELEASE : std_logic_vector(7 downto 0) := X"00";
  constant GC_FPGA_REV_UPGRADE : std_logic_vector(7 downto 0) := X"00";
  constant GC_FPGA_REV_BUGFIX  : std_logic_vector(7 downto 0) := X"01";
end package;
